#9
dmmishchenko/journey-bot pull request #10
Opened 2023-09-30 10:31 UTC by ESQ0RPI0

a lot of changes, update handler for tests + a lot of additional classes for future usage

2023-09-30 16:02 UTC, dmmishchenko requested changes
Please change name, everything but this is good

2023-10-03 16:47 UTC, dmmishchenko approved these changes

2023-10-03 16:49 UTC, ESQ0RPI0 commented
completed update handler and hangfire listener implementation

2023-10-04 20:52 UTC, grivdm approved these changes

2023-10-08 09:30 UTC, merged